CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY,
    username varchar(30) UNIQUE NOT NULL,
    password varchar NOT NULL,
    role varchar(30) NOT NULL,
    created_at timestamp NOT NULL
);

DROP TABLE Person;

UPDATE Person SET role='ROLE_ADMIN' WHERE id=1;

INSERT INTO Person(username, password, role) VALUES
('user','password','USER'),('admin','password','ADMIN');