CREATE TABLE Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(30) UNIQUE NOT NULL,
    password varchar NOT NULL,
    role varchar(30) NOT NULL,
    created_at timestamp NOT NULL
);

DROP TABLE Person;
DROP TABLE Comments;

UPDATE Person SET role='ROLE_ADMIN' WHERE id=1;

-- /////////////////////////////////////////////

CREATE TABLE Comments(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id int NOT NULL REFERENCES Person(id) ON DELETE SET NULL,
    text varchar(3000) NOT NULL,
    count_likes int,
    count_dislikes int,
    created_at timestamp
);

INSERT INTO Comments(owner_id,text)
VALUES
    (1,'text1 text1 text1 text1 text1 text1 text1'),
    (1,'text2 text2 text2 text2 text2 text2 text2'),
    (1,'text3 text3 text3 text3 text3 text3 text3');
