#   команда запуска docker-compose -f docker-compose-kafka.yml up -d
version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 127.0.0.1:2181:2181
    networks:
      - project_net

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 127.0.0.1:9092:9092
    networks:
      - project_net
    depends_on:
      - zookeeper


networks:
  project_net:
    driver: bridge