#   этот вариант файла предназначен для хранения в публичном репозитории git
#   перед запуском добавить пароль БД идентичный в файле application.properties
#   команда запуска docker-compose -f docker-compose(withoutPass).yml up -d
version: "3.5"
services:
  project_app:
    image: kmnpetr/project:latest
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - project_net
    depends_on:
      - progect_database

  ngnix:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - 'nginx:/usr/share/nginx/html'
      - 'nginx_conf:/etc/nginx/conf.d'
    networks:
      - project_net
    depends_on:
      - project_app

  progect_database:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=postgres
    networks:
      - project_net
    volumes:
      - 'progect_database:/var/lib/postgresql/data'

volumes:
  nginx:
  nginx_conf:
  progect_database:

networks:
  project_net:
    driver: bridge