#   этот вариант файла предназначен для хранения в публичном репозитории git
#   перед запуском добавить пароль БД идентичный в файле application.properties
#   email и имя хоста в certbot
#   команда запуска docker-compose -f docker-compose-dev.yml up -d
version: "3.5"
services:
  project_app:
    image: kmnpetr/project:latest
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - project_net
    depends_on:
      - progect_database


  progect_database:
    image: postgres:14.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_USER=<user>
    networks:
      - project_net
    volumes:
      - 'progect_database:/var/lib/postgresql/data'

  ngnix:
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - '/home/nginx-src:/etc/nginx/conf.d/'
    networks:
      - project_net
    depends_on:
      - project_app


volumes:
  progect_database:

networks:
  project_net:
    driver: bridge