#   этот вариант файла предназначен для хранения в публичном репозитории git
#   перед запуском добавить пароль БД идентичный в файле application.properties
#   email и имя хоста в certbot
#   команда запуска docker-compose -f docker-compose-dev.yml up -d
version: "3.5"
services:
  project_app:
    image: kmnpetr/project:latest
    container_name: project_app
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - project_net
    depends_on:
      - progect_database
      - kafka


  progect_database:
    image: postgres:14.3-alpine
    container_name: progect_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
    networks:
      - project_net
    volumes:
      - 'progect_database:/var/lib/postgresql/data'

  ngnix:
    image: nginx:1.20-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - '/home/nginx-src:/etc/nginx/conf.d/'
    networks:
      - project_net
    depends_on:
      - project_app


  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - 127.0.0.1:2181:2181
    networks:
      - project_net

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 127.0.0.1:9092:9092
    networks:
      - project_net
    depends_on:
      - zookeeper


volumes:
  progect_database:

networks:
  project_net:
    driver: bridge